ipa.networks <- c(
  "Abnormal Morphology of Cardiovascular System",
  "Angiogenesis",
  "Apoptosis",
  "Apoptosis of Muscle Cells",
  "Apoptosis of Smooth Muscle Cells",
  "Apoptosis of Vascular Smooth Muscle Cells",
  "Concentration of ATP",
  "B-Cell Neoplasm",
  "BMP Signaling Pathway",
  "Development of Neurons ",
  "Effects of PIP2 Hydrolysis",
  "Extracellular Matrix Organization",
  "Function of skeletal muscle",
  "GABA Receptor Activation",
  "Glucose Metabolism Disorder",
  "Glycation Signaling Pathway",
  "Glycosaminoglycan Metabolism",
  "Glyoxylate Metabolism and glycine Degradation",
  "GM-CSF Signaling",
  "GP6 Signaling Pathway",
  "Granzyme A Signaling",
  "Growth of Neurites",
  "IL-6 Signaling",
  "Inflammatory Response",
  "Insulin Secretion Signaling",
  "Integrin Cell Surface Interactions",
  "Malignant Lymphocytic Neoplasm",
  "Metabolism of Reactive Oxygen Species",
  "Migration of Smooth Muscle Cells",
  "Mitochondrial Dysfunction",
  "mTOR Signaling",
  "Muscle Contraction",
  "Natural Killer Cell Signaling",
  "Necrosis",
  "Neoplasia of Leukocytes",
  "Neuritogenesis",
  "Neuroinflammation Signaling Pathways",
  "Neurovascular Coupling Signaling",
  "Neutrophil Degranulation",
  "Neutrophil Extracellular Trap Signaling",
  "Oxidative Phosphorylation",
  "Pancreatic Secretion Signaling",
  "Parkinson's Signaling",
  "PPAR Signaling",
  "Proliferation of Neural Cells",
  "Proliferation of Neuronal Cells",
  "PTEN Regulation",
  "PTEN Signaling",
  "Reelin Signaling in Neurons",
  "Regulation of Insulin-like Growth Factor",
  "Regulation of the Epithelial Mesenchymal Transition by Growth Factors Pathway",
  "Respiratory Electron Transport",
  "RHOGDI Signaling",
  "Semaphorin Neuronal Repulsive Signaling ",
  "Sirtuin Signaling",
  "Smooth Muscle Contraction",
  "SNARE Signaling",
  "Striated Muscle Contraction",
  "Synaptogenesis Signaling",
  "Synthesis of Reactive Oxygen Species",
  "TCF Dependent Signaling in Response to WNT ",
  "TGF",
  "Translocation of SLC2A4",
  "Vasculogenesis",
  "White Adipose Tissue Browning Pathway",
  "Wound Healing"
  )
