############################################################
# Title: Between-cohort heterogeneity analysis (METAL output)
# Project: Adiponectin EWAS – Sensitivity Analysis
#
# Author: Muhulo Muhau Mungamba
# Date: 2025-10-09
#
# Description:
# This script extracts and summarizes between-cohort
# heterogeneity statistics (Cochran’s Q and I²) from METAL
# meta-analysis output for genome-wide significant CpG sites.
#
# This analysis evaluates whether meta-analytic associations
# are consistent between RODAM (Ghanaians) and AADM (Nigerians).
#
# Notes:
# - Heterogeneity statistics are generated by METAL
# - No re-estimation of effects is performed
############################################################

rm(list = ls())
gc()

options(stringsAsFactors = FALSE)

library(dplyr)

# ---- Set working directory (EDIT AS NEEDED) ----
setwd("/home/P083854/lkg/Rodam/MUHAU_RODAM/EWAS_Adiponectin/Manuscript/Publication_ready/eBioMedicine/Revision/")

# ---- Load METAL meta-analysis output ----
metal_file <- "Metal_files/Adiponectin_RODAMwsite_AADM_T2D_cases_controls_metaanalysisN1_wFDR.txt"

meta <- read.delim(
  metal_file,
  header = TRUE,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

# ---- CpGs reported in the manuscript ----
top_cpgs <- c(
  "cg03546163",  # FKBP5
  "cg02561343",  # UST
  "cg23969380"   # ADGRD1
)

# ---- Extract heterogeneity statistics ----
heterogeneity_table <- meta %>%
  filter(MarkerName %in% top_cpgs) %>%
  select(
    MarkerName,
    Zscore,
    P.value,
    FDR,
    HetISq,
    HetChiSq,
    HetDf,
    HetPVal
  )

# ---- Add interpretation ----
heterogeneity_table <- heterogeneity_table %>%
  mutate(
    I2_Category = case_when(
      HetISq < 25 ~ "Low",
      HetISq >= 25 & HetISq < 50 ~ "Moderate",
      HetISq >= 50 ~ "High"
    ),
    Heterogeneity_Test = ifelse(
      HetPVal < 0.05,
      "Significant heterogeneity",
      "No significant heterogeneity"
    )
  )

print(heterogeneity_table)

# ---- Save output ----
outdir <- "06_Sensitivity_Analysis/06b_Between_Cohort_Heterogeneity/outputs"
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

write.table(
  heterogeneity_table,
  file.path(outdir, "TopCpGs_Heterogeneity_Summary.txt"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

############################################################
# END OF SCRIPT
############################################################
